modLoader="javafml"
loaderVersion="${loader_version}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/easy-piglins/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://update.maxhenkel.de/neoforge/easy_piglins"
displayURL="https://www.curseforge.com/minecraft/mc-mods/easy-piglins"
authors="${mod_vendor}"
description='''Easy Piglins'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"