modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/easy-piglins/issues"
[[mods]]
modId = "easy_piglins"
version = "${mod_version}"
displayName = "Easy Piglins"
updateJSONURL = "https://update.maxhenkel.de/forge/easy_piglins"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/easy-piglins"
authors = "Max Henkel"
description = '''Easy Piglins'''
[[dependencies.easy_piglins]]
modId = "forge"
mandatory = true
versionRange = "${forge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.easy_piglins]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"